# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wonder What You Were
# tagline:             'eco-conscious accessories for you + your home. vintage, repurposed + scrap fabrics.'
description:         'eco-conscious accessories for you + your home. vintage, repurposed + scrap fabrics.'
url:                 http://wonderwhatyouwere.com
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Cindy Choua

# Custom vars
version:             1.0.0
